name: ego-dev
base: core20
version: "0.4.0"
summary: EGo lets you build, debug und run Go apps on Intel SGX!
description: EGo is a framework for building confidential apps in Go. Confidential apps run in always-encrypted and verifiable enclaves on Intel SGX-enabled hardware.

grade: stable
confinement: classic

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  ego:
    command: opt/ego/bin/ego
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  ego-go:
    command: opt/ego/bin/ego-go
  ego-gdb:
    command: opt/ego/bin/ego-gdb
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

parts:
  ego:
    source: https://github.com/edgelesssys/ego/releases/download/v0.4.0/ego_0.4.0_amd64.deb
    source-checksum: "sha256/8397b839bc9117e1e6c512e088599c83b0d0e4306973c07cf5202a00f6868780"
    source-type: deb
    plugin: dump
    build-attributes: [no-patchelf] # needed otherwise Snap breaks the go binary, causing it to segfault on launch
    # fix symlinks in .deb release package, they point outside of the snap environment and snapcraft will automatically add them anyway
    override-build: |
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego-go
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego-gdb
      rm -f $SNAPCRAFT_PART_BUILD/usr/local/bin/ego
      snapcraftctl build
    stage-packages:
      [
        libsgx-enclave-common,
        libsgx-dcap-ql,
        libsgx-dcap-ql-dev,
      ]

package-repositories:
  - type: apt
    components: [main]
    suites: [bionic]
    key-id: 35BFD5E1AEFFA8C4996DDD0DAA65AD26261B320B
    url: https://download.01.org/intel-sgx/sgx_repo/ubuntu
